FROM ubuntu:20.04
RUN apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq install -y \
    vim emacs nano \
    build-essential curl git lib32stdc++-9-dev \
    libc6-dev-i386 nodejs npm python3-dev python3-pip

RUN pip3 install colorama prompt-toolkit pygments
RUN pip3 install frida-tools frida
RUN npm install frida

WORKDIR /frida

# Install JDK
RUN mkdir /java
RUN curl -L -o- https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.13%2B8/OpenJDK11U-jdk-shenandoah_x64_linux_11.0.13_8.tar.gz | tar xz -C /java

# Get minecraft server v1.3.1
RUN curl https://launcher.mojang.com/v1/objects/82563ce498bfc1fc8a2cb5bf236f7da86a390646/server.jar -o /java/minecraftserver.1.3.1.jar
