FROM ubuntu:20.04
RUN apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq install -y \
    vim emacs nano \
    build-essential curl git lib32stdc++-9-dev \
    libc6-dev-i386 nodejs npm python3-dev python3-pip
    python3.8 gcc-multilib g++-multilib

RUN pip3 install colorama prompt-toolkit pygments

RUN git clone --recurse-submodules https://github.com/frida/frida.git /frida

WORKDIR /frida

RUN make core-linux-x86_64
RUN make python-linux-x86_64 PYTHON=$(which python3.8)

# Setup Frida python/tools (so we can run frida on the cli)
ENV FRIDA_EXTENSION=/frida/build/frida-linux-x86_64/lib/python3.8/site-packages/_frida.so

RUN cd /frida/frida-python && \
    FRIDA_VERSION=$(git describe --tags) \
    python3.8 setup.py install

RUN cd /frida/frida-tools && make && python3.8 setup.py install
